package com.yab.multitenantERP.enums;

public enum EmployeeDocumentType {
    NATIONAL_ID,
    PASSPORT,
    DRIVER_LICENSE,
    SOCIAL_SECURITY_CARD,
    BIRTH_CERTIFICATE,
    EMPLOYMENT_CONTRACT,
    OFFER_LETTER,
    PAYSLIP,
    BANK_STATEMENT,
    TAX_CERTIFICATE,
    MEDICAL_CERTIFICATE,
    INSURANCE_POLICY,
    VISA,
    WORK_PERMIT,
    ACADEMIC_CERTIFICATE,
    TRAINING_CERTIFICATE,
    PERFORMANCE_REVIEW,
    PROMOTION_LETTER,
    RESIGNATION_LETTER,
    EXPERIENCE_LETTER,
    NON_DISCLOSURE_AGREEMENT,
    BACKGROUND_CHECK_REPORT,
    EMERGENCY_CONTACT_FORM,
    ADDRESS_PROOF,
    BENEFICIARY_NOMINATION_FORM
}
