package com.yab.multitenantERP.enums;

public enum Status {
    ACTIVE,
    INACTIVE,
    PENDING_APPROVAL,
    SUSPENDED,
    CLOSED,
    UNDER_CONSTRUCTION,
    RELOCATING,
    MERGING,
    FULL_TIME,
    PART_TIME,
    CONTRACTUAL,
    TEMPORARY,
    FREELANCE,
    INTERNSHIP,
    PROBATIONARY,
    SELF_EMPLOYED,
    ON_CALL,
    EXEMPT,
    NON_EXEMPT,
    REMOTE,
    SEASONAL,
    RETIRED,
    VOLUNTEER,
    SABBATICAL,
    JOB_SHARING,
    MATERNITY_PATERNITY_LEAVE;

}
